#!/bin/bash
export $(cat .env | grep -v ^\#)

if test $1 = "none" ; then
  echo "proxy設定を無効化しました"
  git config --global --unset http.proxy
  git config --global --unset https.proxy
elif test $1 = "lab" ; then
  echo "研究室設定をしました"
  git config --global http.proxy $MY_PROXY_HTTP
  git config --global https.proxy $MY_PROXY_HTTPS
else
  echo "設定が見当たりません"
fi
