#!/bin/bash
export $(cat .env | grep -v ^\#)

if test $1 = "init"; then
  echo input proxy_http :
  #一度に複数の変数へ入力、スペースで区切る
  read proxy_http
  #結果を表示する。
  echo "set" $proxy_http

  echo "MY_PROXY_HTTP="$proxy_http > .env

  echo input proxy_https :
  #一度に複数の変数へ入力、スペースで区切る
  read proxy_https
  #結果を表示する。
  echo "set" $proxy_https

  echo "MY_PROXY_HTTP="$proxy_http >> .env

  exit 2
fi

if test $1 = "none" ; then
  echo "proxy設定を無効化しました"
  git config --global --unset http.proxy
  git config --global --unset https.proxy

  if type "yarn" > /dev/null 2>&1; then
    yarn config delete proxy
    yarn config delete https-proxy
  fi

elif test $1 = "lab" ; then
  echo "研究室設定をしました"
  git config --global http.proxy $MY_PROXY_HTTP
  git config --global https.proxy $MY_PROXY_HTTPS

  if type "yarn" > /dev/null 2>&1; then
    yarn config set proxy $MY_PROXY_HTTP
    yarn config set https-proxy $MY_PROXY_HTTPS
  fi
else
  echo "設定が見当たりません"
fi
